name: Terraform Infrastructure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::394151408055:role/GIthub-OIDC-Role
          aws-region: us-east-1
          
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan --auto-approve

      - name: Terraform apply
        run: terraform apply --auto-approve